
project_id = "ioeihnoxvtpxtqhxklpw"

[api]
[api.schema]

[db]

[db.pooler]

[realtime]

[functions]

[functions.upload-epub]
verify_jwt = false

[functions.generateStory]
verify_jwt = true

[functions.retry-story]
verify_jwt = true

[functions.n8n-story-webhook]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = true

[functions.tts-elevenlabs]
verify_jwt = true
