
project_id = "ioeihnoxvtpxtqhxklpw"

[api]
[api.schema]

[db]

[db.pooler]

[realtime]

[functions]

[functions.upload-epub]
verify_jwt = false

[functions.generate-story]
verify_jwt = true

[functions.retry-story]
verify_jwt = true

