
project_id = "ioeihnoxvtpxtqhxklpw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv6"
tenant_id = "realtime-dev"
max_slot_name_length = 63

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.connectivity-test]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.generateStory]
verify_jwt = true

[functions.n8n-audio-callback]
verify_jwt = false

[functions.n8n-story-webhook]
verify_jwt = false

[functions.n8n-story-completion-callback]
verify_jwt = false

[functions.regenerateStory]
verify_jwt = true

[functions.retry-story]
verify_jwt = true

[functions.testConnection]
verify_jwt = false

[functions.tts-elevenlabs]
verify_jwt = true

[functions.tts-test]
verify_jwt = false

[functions.upload-audio-from-n8n]
verify_jwt = false

[functions.upload-epub]
verify_jwt = true
