
name: 'Configuration du compte de service Firebase'
description: 'Configure le compte de service Firebase pour le déploiement'

inputs:
  firebase-service-account:
    description: 'Compte de service Firebase au format JSON'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configuration du compte de service Firebase
      shell: bash
      env:
        FIREBASE_SERVICE_ACCOUNT_JSON: ${{ inputs.firebase-service-account }}
      run: |
        if [ -z "$FIREBASE_SERVICE_ACCOUNT_JSON" ]; then
          echo "❌ ERREUR: FIREBASE_SERVICE_ACCOUNT manquant"
          exit 1
        fi
        
        echo "$FIREBASE_SERVICE_ACCOUNT_JSON" > /tmp/firebase-service-account.json
        chmod 600 /tmp/firebase-service-account.json
        
        if ! jq empty /tmp/firebase-service-account.json; then
          echo "❌ ERREUR: JSON du compte de service invalide"
          exit 1
        fi
        
        echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase-service-account.json" >> $GITHUB_ENV
        echo "✅ Compte de service Firebase configuré"
