
import OpenAI from 'openai';
import { type Story } from '../types/story';

export const generateStoryWithAI = async (
  objective: string, 
  childrenNames: string[], 
  apiKey: string
): Promise<Story> => {
  console.log("Starting OpenAI story generation with parameters:", {
    objective,
    childrenNames,
    hasApiKey: !!apiKey
  });
  
  try {
    if (!apiKey) {
      console.error("OpenAI API key is required but not provided");
      throw new Error("La clé API OpenAI est requise");
    }

    console.log("Initializing OpenAI client");
    const openai = new OpenAI({
      apiKey: apiKey
    });

    console.log("Creating OpenAI request with adjusted parameters");
    const completion = await openai.chat.completions.create({
      model: 'gpt-4-0125-preview',
      messages: [
        {
          role: 'system',
          content: `Tu es un expert en création d'histoires pour enfants.

FORMAT DE L'HISTOIRE :
- Longueur : IMPÉRATIF de faire entre 10000-15000 mots (environ 6-8 minutes de lecture)
- Structure narrative fluide et continue, sans découpage visible
- Pas de titre explicite
- Descriptions détaillées et immersives
- Dialogues riches et naturels entre les personnages

RÈGLES FONDAMENTALES :
- Adapte le langage à l'âge de l'enfant
- Crée des personnages mémorables avec des personnalités distinctes
- Utilise des dialogues engageants et naturels
- Ajoute des répétitions stratégiques pour les jeunes enfants
- Évite tout contenu effrayant ou angoissant
- Termine toujours sur une note positive
- Enrichis l'histoire avec des détails sensoriels
- Développe les relations entre les personnages

STRUCTURE CACHÉE (ne pas la rendre visible) :
1. Introduction et mise en contexte (2000-2500 mots)
2. Développement de l'ambiance (2500-3000 mots)
3. Progression de l'histoire (2500-3000 mots)
4. Cœur de l'histoire (2500-3000 mots)
5. Conclusion (2000-2500 mots)`,
        },
        {
          role: 'user',
          content: `Je souhaite créer une histoire personnalisée pour ${childrenNames.join(', ')} avec l'objectif suivant : ${objective}. 
          L'histoire doit suivre la structure donnée tout en restant fluide et naturelle, sans découpage visible en parties.
          Assure-toi que l'histoire soit captivante dès le début pour maintenir l'attention des enfants.
          IMPORTANT : L'histoire doit faire entre 10000 et 15000 mots.`,
        },
      ],
      temperature: 0.8,
      max_tokens: 32000,
      frequency_penalty: 0.2,
      presence_penalty: 0.1,
    });

    console.log("OpenAI response received successfully");
    const generatedText = completion.choices[0].message.content;
    
    if (!generatedText) {
      console.error("Error: No story content generated by OpenAI");
      throw new Error('Aucune histoire n\'a été générée');
    }

    const wordCount = generatedText.split(/\s+/).length;
    console.log(`Story generated with ${wordCount} words`);
    
    if (wordCount < 10000) {
      console.warn("Warning: Story is shorter than expected minimum length");
    }

    console.log("Generating story data");
    const uniqueId = `story_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

    console.log("Formatting story data");
    const storyData: Story = {
      id: uniqueId,
      story_text: generatedText,
      summary: "Résumé en cours de génération...",
      createdAt: new Date().toISOString(),
      title: `Histoire pour ${childrenNames.join(' et ')}`,
      preview: generatedText.substring(0, 200) + "...",
      wordCount: wordCount,
      status: 'pending',
      objective: objective,
      childrenNames: childrenNames,
      _version: 1,
      _lastSync: new Date().toISOString(),
      _pendingWrites: true
    };

    console.log("Story data formatted successfully:", {
      id: storyData.id,
      wordCount: storyData.wordCount,
      status: storyData.status
    });
    
    return storyData;
  } catch (error) {
    console.error("Error during story generation with OpenAI:", error);
    
    // Amélioration de la gestion des erreurs OpenAI
    if (error instanceof OpenAI.APIError) {
      console.error("OpenAI API Error details:", {
        status: error.status,
        type: error.type,
        code: error.code
      });
      throw new Error(`Erreur OpenAI: ${error.message}`);
    }
    
    throw error;
  }
};

