
import OpenAI from 'openai';

export const generateStoryWithAI = async (objective: string, childrenNames: string[], apiKey: string) => {
  console.log("Starting OpenAI story generation");
  console.log("Parameters received:", { objective, childrenNames });
  
  try {
    if (!apiKey) {
      console.error("OpenAI API key is required but not provided");
      throw new Error("La clé API OpenAI est requise");
    }

    console.log("Initializing OpenAI client");
    const openai = new OpenAI({
      apiKey: apiKey
    });

    console.log("Creating OpenAI request");
    const completion = await openai.chat.completions.create({
      model: 'gpt-4',
      messages: [
        {
          role: 'system',
          content: `Tu es un expert en création d'histoires pour enfants.

FORMAT DE L'HISTOIRE :
- Longueur : 6000-10000 mots
- Structure narrative fluide et continue, sans découpage visible
- Pas de titre explicite

RÈGLES FONDAMENTALES :
- Adapte le langage à l'âge de l'enfant
- Crée des personnages mémorables et appropriés
- Utilise des dialogues engageants
- Ajoute des répétitions pour les jeunes enfants
- Évite tout contenu effrayant ou angoissant
- Termine toujours sur une note positive

STRUCTURE CACHÉE (ne pas la rendre visible) :
1. Introduction et mise en contexte
2. Développement de l'ambiance
3. Progression de l'histoire
4. Cœur de l'histoire
5. Conclusion

CONTRAINTES SPÉCIFIQUES :
- Vocabulaire simple et accessible
- Pas de termes liés à l'hypnose
- Grammaire et orthographe impeccables
- Éviter l'excès de superlatifs
- Noms de personnages appropriés
- Univers cohérent et captivant`,
        },
        {
          role: 'user',
          content: `Je souhaite créer une histoire personnalisée pour ${childrenNames.join(', ')} avec l'objectif suivant : ${objective}. 
          L'histoire doit suivre la structure donnée tout en restant fluide et naturelle, sans découpage visible en parties.
          Assure-toi que l'histoire soit captivante dès le début pour maintenir l'attention des enfants.`,
        },
      ],
      temperature: 0.7,
      max_tokens: 4000,
    });

    console.log("OpenAI response received successfully");
    
    const story = completion.choices[0].message.content;
    if (!story) {
      console.error("Error: No story content generated by OpenAI");
      throw new Error('Aucune histoire n\'a été générée');
    }

    console.log("Generating unique ID for story");
    const uniqueId = `story_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

    console.log("Formatting story data");
    const storyData = {
      id_stories: uniqueId,
      story_text: story,
      story_summary: "Résumé en cours de génération...",
      status: 'pending',
      createdAt: new Date(),
      title: "Nouvelle histoire",
      preview: story.substring(0, 200) + "..."
    };

    console.log("Story data formatted successfully");
    return storyData;
  } catch (error) {
    console.error("Error during story generation with OpenAI:", error);
    throw error;
  }
};
