
import OpenAI from 'openai';

export const generateStoryWithAI = async (objective: string, childrenNames: string[], apiKey: string) => {
  console.log("Starting OpenAI story generation");
  console.log("Parameters received:", { objective, childrenNames });
  
  try {
    if (!apiKey) {
      console.error("OpenAI API key is required but not provided");
      throw new Error("La clé API OpenAI est requise");
    }

    console.log("Initializing OpenAI client");
    const openai = new OpenAI({
      apiKey: apiKey
    });

    console.log("Creating OpenAI request");
    const completion = await openai.chat.completions.create({
      model: 'gpt-4-0125-preview',
      messages: [
        {
          role: 'system',
          content: `Tu es un expert en création d'histoires pour enfants.

FORMAT DE L'HISTOIRE :
- Longueur : IMPÉRATIF de faire entre 10000-15000 mots (environ 6-8 minutes de lecture)
- Structure narrative fluide et continue, sans découpage visible
- Pas de titre explicite
- Descriptions détaillées et immersives
- Dialogues riches et naturels entre les personnages

RÈGLES FONDAMENTALES :
- Adapte le langage à l'âge de l'enfant
- Crée des personnages mémorables avec des personnalités distinctes
- Utilise des dialogues engageants et naturels
- Ajoute des répétitions stratégiques pour les jeunes enfants
- Évite tout contenu effrayant ou angoissant
- Termine toujours sur une note positive
- Enrichis l'histoire avec des détails sensoriels
- Développe les relations entre les personnages

STRUCTURE CACHÉE (ne pas la rendre visible) :
1. Introduction et mise en contexte (2000-2500 mots) :
   - Cadre sécurisant et familier détaillé
   - Personnages principaux introduits naturellement
   - Description sensorielle riche de l'environnement
   - Transition douce vers l'aventure

2. Développement de l'ambiance (2500-3000 mots) :
   - Descriptions sensorielles immersives
   - Éléments naturels ou fantastiques détaillés
   - Ton calme et rassurant
   - Métaphores apaisantes et imagées

3. Progression de l'histoire (2500-3000 mots) :
   - Langage indirect et suggestions positives
   - Introduction de compagnons bienveillants
   - Symboles rassurants
   - Progression naturelle avec suspense léger

4. Cœur de l'histoire (2500-3000 mots) :
   - Aventure captivante mais apaisante
   - Descriptions immersives détaillées
   - Rencontres positives mémorables
   - Rythme équilibré avec moments calmes

5. Conclusion (2000-2500 mots) :
   - Renforcement du sentiment de sécurité
   - Résolution satisfaisante
   - Messages positifs subtilement intégrés
   - Transition douce vers la fin

CONTRAINTES SPÉCIFIQUES :
- Vocabulaire riche mais accessible
- Pas de termes liés à l'hypnose
- Grammaire et orthographe impeccables
- Éviter l'excès de superlatifs
- Noms de personnages appropriés et mémorables
- Univers cohérent et captivant
- Descriptions sensorielles enrichies`,
        },
        {
          role: 'user',
          content: `Je souhaite créer une histoire personnalisée pour ${childrenNames.join(', ')} avec l'objectif suivant : ${objective}. 
          L'histoire doit suivre la structure donnée tout en restant fluide et naturelle, sans découpage visible en parties.
          Assure-toi que l'histoire soit captivante dès le début pour maintenir l'attention des enfants.
          IMPORTANT : L'histoire doit faire entre 10000 et 15000 mots.`,
        },
      ],
      temperature: 0.8,
      max_tokens: 8000,
      frequency_penalty: 0.2,
      presence_penalty: 0.1,
    });

    console.log("OpenAI response received successfully");
    const story = completion.choices[0].message.content;
    
    if (!story) {
      console.error("Error: No story content generated by OpenAI");
      throw new Error('Aucune histoire n\'a été générée');
    }

    // Vérification de la longueur
    const wordCount = story.split(/\s+/).length;
    console.log(`Story generated with ${wordCount} words`);
    
    if (wordCount < 10000) {
      console.warn("Warning: Story is shorter than expected minimum length");
    }

    console.log("Generating unique ID for story");
    const uniqueId = `story_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

    console.log("Formatting story data");
    const storyData = {
      id_stories: uniqueId,
      story_text: story,
      story_summary: "Résumé en cours de génération...",
      createdAt: new Date(),
      title: `Histoire pour ${childrenNames.join(' et ')}`,
      preview: story.substring(0, 200) + "...",
      wordCount: wordCount,
    };

    console.log("Story data formatted successfully");
    return storyData;
  } catch (error) {
    console.error("Error during story generation with OpenAI:", error);
    throw error;
  }
};
