
name: Deploy to Firebase
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
      
      - name: Configuration de Node.js
        uses: ./.github/workflows/actions/setup-node
      
      - name: Installation des dépendances pour Functions
        uses: ./.github/workflows/actions/install-dependencies
        with:
          working-directory: functions
          codebase: functions
      
      - name: Installation des dépendances pour Functions V2
        uses: ./.github/workflows/actions/install-dependencies
        with:
          working-directory: functions-v2
          codebase: functions-v2
      
      - name: Installation des dépendances pour l'app principale
        run: npm ci
      
      - name: Build de l'application
        run: npm run build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
      
      - name: Configuration des variables d'environnement
        uses: ./.github/workflows/actions/setup-env
        with:
          working-directory: functions-v2
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          google-cloud-project: ${{ secrets.GOOGLE_CLOUD_PROJECT || 'calmi-99482' }}
      
      - name: Configuration du compte de service Firebase
        uses: ./.github/workflows/actions/setup-firebase-service
        with:
          firebase-service-account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      
      - name: Build et déploiement Firebase
        uses: ./.github/workflows/actions/build-deploy
        with:
          working-directory: functions-v2
          project-id: ${{ secrets.GOOGLE_CLOUD_PROJECT || 'calmi-99482' }}
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
          deploy-target: functionsV2

