
name: Deploy to Firebase Staging
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Clean npm cache and install dependencies for functions
        run: |
          cd functions
          rm -rf node_modules
          rm -f package-lock.json
          npm install --no-audit --no-fund
          
      - name: Clean npm cache and install dependencies for functions-v2
        run: |
          cd functions-v2
          rm -rf node_modules lib
          rm -f package-lock.json
          # Utiliser npm install au lieu de npm ci
          npm install --no-package-lock
          npm list --depth=0
          echo "Vérification des dépendances clés:"
          npm list firebase-functions || true
          npm list firebase-admin || true
          npm list openai || true
          
      - name: Install Dependencies for main app
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        
      - name: Setup Environment Variables
        run: |
          cd functions-v2
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
          echo "GOOGLE_CLOUD_PROJECT=${{ secrets.GOOGLE_CLOUD_PROJECT || 'calmi-99482' }}" >> .env
          
          # Debug information
          echo "Variables d'environnement configurées:"
          echo "GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT || 'calmi-99482' }}"
          echo "Présence de OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY != '' }}"
      
      - name: Setup Firebase service account
        id: setup-firebase
        run: |
          # Vérification des variables disponibles
          echo "Vérification des secrets disponibles..."
          echo "FIREBASE_TOKEN présent: ${{ secrets.FIREBASE_TOKEN != '' }}"
          echo "FIREBASE_SERVICE_ACCOUNT présent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT != '' }}"
          echo "GOOGLE_APPLICATION_CREDENTIALS_JSON présent: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON != '' }}"
          
          # Utiliser l'un ou l'autre des comptes de service disponibles
          if [ "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" != "" ]; then
            echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > /tmp/firebase-service-account.json
            echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase-service-account.json" >> $GITHUB_ENV
            echo "service_account_path=/tmp/firebase-service-account.json" >> $GITHUB_OUTPUT
            echo "✅ Compte de service Firebase configuré via FIREBASE_SERVICE_ACCOUNT"
          elif [ "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" != "" ]; then
            echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > /tmp/firebase-service-account.json
            echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase-service-account.json" >> $GITHUB_ENV
            echo "service_account_path=/tmp/firebase-service-account.json" >> $GITHUB_OUTPUT
            echo "✅ Compte de service Firebase configuré via GOOGLE_APPLICATION_CREDENTIALS_JSON"
          else
            echo "⚠️ ATTENTION: Aucun compte de service Firebase configuré"
            echo "Le déploiement pourrait échouer. Configurez FIREBASE_SERVICE_ACCOUNT ou GOOGLE_APPLICATION_CREDENTIALS_JSON"
          fi
          
      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest
        
      - name: Build Functions v2
        run: |
          cd functions-v2
          npm run build
          echo "Build des fonctions v2 terminé"
          echo "Contenu du dossier lib:"
          ls -la lib/
        
      - name: Deploy to Firebase Staging
        run: |
          # Vérifier la présence de variables d'environnement
          echo "GOOGLE_APPLICATION_CREDENTIALS défini: $(if [ -n "$GOOGLE_APPLICATION_CREDENTIALS" ]; then echo "Oui"; else echo "Non"; fi)"
          if [ -f "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
            echo "Le fichier d'identifiants existe"
          else 
            echo "⚠️ ATTENTION: Le fichier d'identifiants n'existe pas"
          fi
          
          # Déploiement avec logs détaillés
          firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --only hosting:staging,functions,functions:v2 --project ${{ secrets.GOOGLE_CLOUD_PROJECT || 'calmi-99482' }} --debug
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.setup-firebase.outputs.service_account_path }}
