
name: Deploy to Firebase
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Clean npm cache and install dependencies for functions
        run: |
          cd functions
          rm -rf node_modules
          rm -f package-lock.json
          npm install --no-audit --no-fund
          ls -la node_modules/firebase-admin
          
      - name: Clean npm cache and install dependencies for functions-v2
        run: |
          cd functions-v2
          rm -rf node_modules lib
          rm -f package-lock.json
          npm install --no-package-lock
          npm list --depth=0
          ls -la node_modules/firebase-admin
          
      - name: Install Dependencies for main app
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        
      - name: Setup Environment Variables
        run: |
          cd functions-v2
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
          echo "GOOGLE_CLOUD_PROJECT=${{ secrets.GOOGLE_CLOUD_PROJECT || 'calmi-99482' }}" >> .env
          
          echo "Variables d'environnement configurées:"
          echo "GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT || 'calmi-99482' }}"
          echo "Présence de OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY != '' }}"
      
      - name: Setup Firebase Service Account (Simplified)
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          # Créer le fichier de service account simplement
          echo "$FIREBASE_SERVICE_ACCOUNT_JSON" > /tmp/firebase-service-account.json
          
          # Vérifier que le fichier existe et n'est pas vide
          if [ ! -s "/tmp/firebase-service-account.json" ]; then
            echo "❌ ERREUR: Le fichier de compte de service est vide ou n'existe pas."
            echo "Veuillez vérifier que le secret FIREBASE_SERVICE_ACCOUNT est correctement configuré."
            exit 1
          else
            echo "✅ Compte de service Firebase configuré avec succès"
            echo "Taille du fichier: $(wc -c < /tmp/firebase-service-account.json) octets"
          fi
          
          # Exporter le chemin vers le fichier comme variable d'environnement
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase-service-account.json" >> $GITHUB_ENV
      
      - name: Check Service Account File
        run: |
          if [ -f "/tmp/firebase-service-account.json" ]; then
            echo "✅ Le fichier de service account existe"
            stat /tmp/firebase-service-account.json
          else
            echo "❌ Le fichier de service account n'existe pas"
            ls -la /tmp/
            exit 1
          fi
      
      - name: Install Firebase CLI
        run: |
          npm uninstall -g firebase-tools
          npm install -g firebase-tools@latest
          firebase --version
      
      - name: Création des fichiers functions.yaml
        run: |
          # Pour functions
          cd functions
          echo "# Configuration Firebase Functions" > functions.yaml
          echo "specVersion: v1" >> functions.yaml
          echo "functions:" >> functions.yaml
          echo "  - source: ." >> functions.yaml
          echo "    codebase: default" >> functions.yaml
          echo "    runtime: nodejs20" >> functions.yaml
          echo "    memory: 1GB" >> functions.yaml
          echo "    timeout: 540s" >> functions.yaml
          cat functions.yaml
          cd ..
          
          # Pour functions-v2
          cd functions-v2
          echo "# Configuration Firebase Functions v2" > functions.yaml
          echo "specVersion: v1" >> functions.yaml
          echo "functions:" >> functions.yaml
          echo "  - source: ." >> functions.yaml
          echo "    codebase: v2" >> functions.yaml
          echo "    runtime: nodejs20" >> functions.yaml
          echo "    memory: 1GB" >> functions.yaml
          echo "    timeout: 540s" >> functions.yaml
          cat functions.yaml
          cd ..
      
      - name: Build Functions
        run: |
          cd functions
          npm run build
          echo "Build des fonctions terminé"
          echo "Contenu du dossier lib:"
          ls -la lib/
          
          # Création d'un package.json dans lib
          echo "{\"main\": \"index.js\", \"dependencies\": {\"firebase-admin\": \"^13.0.2\", \"firebase-functions\": \"^6.3.1\"}}" > lib/package.json
          
          # Copie manuelle des dépendances critiques
          echo "Copie des dépendances dans lib..."
          mkdir -p lib/node_modules
          cp -r node_modules/firebase-admin node_modules/firebase-functions lib/node_modules/
          ls -la lib/node_modules
          
      - name: Build Functions v2
        run: |
          cd functions-v2
          npm run build
          echo "Build des fonctions v2 terminé"
          echo "Contenu du dossier lib:"
          ls -la lib/
          
          # Création d'un package.json dans lib
          echo "{\"main\": \"index.js\", \"dependencies\": {\"firebase-admin\": \"^13.0.2\", \"firebase-functions\": \"^6.3.1\"}}" > lib/package.json
          
          # Copie manuelle des dépendances critiques
          echo "Copie des dépendances dans lib..."
          mkdir -p lib/node_modules
          cp -r node_modules/firebase-admin node_modules/firebase-functions node_modules/@google-cloud node_modules/cors node_modules/dotenv node_modules/openai lib/node_modules/
          ls -la lib/node_modules
        
      - name: Deploy to Firebase
        run: |
          echo "Déploiement sur le projet: ${{ secrets.GOOGLE_CLOUD_PROJECT || 'calmi-99482' }}"
          
          # Configuration du NODE_PATH pour aider à trouver les modules
          export NODE_PATH="$PWD/functions/lib/node_modules:$PWD/functions-v2/lib/node_modules:$NODE_PATH"
          echo "NODE_PATH=$NODE_PATH"
          
          # Création d'un firebase.json temporaire
          cp firebase.json firebase.json.bak
          cat > firebase.json << EOL
{
  "functions": [
    {
      "source": "functions",
      "codebase": "default",
      "runtime": "nodejs20",
      "ignore": [
        "node_modules",
        ".git",
        "firebase-debug.log",
        "firebase-debug.*.log"
      ]
    },
    {
      "source": "functions-v2",
      "codebase": "v2",
      "runtime": "nodejs20",
      "ignore": [
        "node_modules",
        ".git",
        "firebase-debug.log",
        "firebase-debug.*.log"
      ]
    }
  ],
  "hosting": [
    {
      "target": "production",
      "public": "dist",
      "ignore": [
        "firebase.json",
        "**/.*",
        "**/node_modules/**"
      ],
      "rewrites": [
        {
          "source": "**",
          "destination": "/index.html"
        }
      ]
    },
    {
      "target": "staging",
      "public": "dist",
      "ignore": [
        "firebase.json",
        "**/.*",
        "**/node_modules/**"
      ],
      "rewrites": [
        {
          "source": "**",
          "destination": "/index.html"
        }
      ]
    }
  ]
}
EOL
          
          # Déploiement avec debug
          firebase deploy --only hosting,functions,functions:v2 \
            --project ${{ secrets.GOOGLE_CLOUD_PROJECT || 'calmi-99482' }} \
            --token "${{ secrets.FIREBASE_TOKEN }}" \
            --debug
          
          # Restauration du firebase.json original
          mv firebase.json.bak firebase.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/firebase-service-account.json
